# Generated by Django 5.0.1 on 2024-02-05 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_album_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='tracks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.track'),
        ),
    ]
