# Generated by Django 5.0.1 on 2024-02-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicauthor',
            name='band_members',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musicauthor',
            name='record_abel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
