# Generated by Django 5.0.1 on 2024-02-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_musicauthor_band_members_musicauthor_record_abel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicauthor',
            old_name='record_abel',
            new_name='record_label',
        ),
    ]
